### ISSUE TITLE
NPE on CRYO run

### ISSUE THREAD

**Issue by baranowb** [jboss-set/aphrodite#213]
Exception in thread "main" java.lang.NullPointerException
        at org.kohsuke.github.GHCommitPointer.getCommit(GHCommitPointer.java:95)
        at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.pullRequestToPullRequest(GitHubWrapper.java:100)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.toAphroditePullRequests(GitHubWrapper.java:70)
        at org.jboss.set.aphrodite.repository.services.github.GitHubRepositoryService.getPullRequestsByState(GitHubRepositoryService.java:157)
        at org.jboss.set.aphrodite.Aphrodite.getPullRequestsByState(Aphrodite.java:624)
        at org.jboss.set.cryo.Cryo.fetchPRList(Cryo.java:259)
        at org.jboss.set.cryo.Cryo.init(Cryo.java:127)
        at org.jboss.set.cryo.Cryo.createStorage(Cryo.java:339)
        at org.jboss.set.cryo.Main.main(Main.java:86)

Ran against EAP

**Comment by baranowb** [comment]
Caused by deleted repo and new changes.

https://github.com/jbossas/jboss-eap7/pull/3288/commits
