### ISSUE TITLE
No issues found which correspond to url: https://issues.redhat.com/browse/ENTSBT-448

### ISSUE THREAD

**Issue by cmoulliard** [jboss-set/aphrodite#216]
## Issue

I can access to this issue if I copy/paste this URL within the browser bar `https://issues.redhat.com/browse/ENTSBT-448`
but aphrodite cannot find it

### Code

See: https://github.com/snowdrop/jira-tool/blob/2a298948d3e917eb9eaa369f971ea3070fb59c19/aphrodite/src/main/java/dev/snowdrop/jira/set/AphroditeClient.java#L50

```
    private void getIssue(String issueKey) throws Exception {
        URL url = new URL(jiraServerUri + "/browse/" + issueKey); // https://issues.redhat.com/browse/ENTSBT-448
        LOG.info("Url : " + url);
        LOG.info("Description : " + aphrodite.getIssue(url).getDescription());
    }
```

### Error
```
Exception in thread "main" org.jboss.set.aphrodite.spi.NotFoundException: No issues found which correspond to url: https://issues.redhat.com/browse/ENTSBT-448
        at org.jboss.set.aphrodite.Aphrodite.getIssue(Aphrodite.java:235)
        at dev.snowdrop.jira.set.AphroditeClient.getIssue(AphroditeClient.java:53)
        at dev.snowdrop.jira.set.AphroditeClient.main(AphroditeClient.java:36)

```

**Comment by wolfc** [comment]
Work for me.
```
Jul 03, 2020 4:22:27 PM dev.snowdrop.jira.set.AphroditeClient getIssue
INFO: Url : https://issues.redhat.com/browse/ENTSBT-448
Jul 03, 2020 4:22:28 PM dev.snowdrop.jira.set.AphroditeClient getIssue
INFO: Description : Optional[h3. Dependency Tree Missing Alignment
```
